#include <nui/core.hpp>
#include <nui/window.hpp>

// This file is generated by nui.
#include <index.hpp>

#include <filesystem>
#include <iostream>

int main(int, char** argv)
{
    using namespace Nui;

    Window window{{.title = "Nui", .debug = true /* may open dev tools */}};
    window.setSize(1600, 950, WebViewHint::WEBVIEW_HINT_NONE);
    window.setHtml(index());

    std::filesystem::path assetsPath = std::filesystem::path{argv[0]}.parent_path() / "assets";
    std::cout << "Assets path: " << assetsPath << std::endl;

    window.setVirtualHostNameToFolderMapping("asset.host", assetsPath.string(), HostResourceAccessKind::Allow);

    window.run();
}